// Code generated by "genenum.exe -typename=TokenType -packagename=tokentype -basedir=. -vectortype=int"

package tokentype_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"
)

type TokenTypeVector [tokentype.TokenType_Count]int

func (es TokenTypeVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "TokenTypeVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			tokentype.TokenType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *TokenTypeVector) Dec(e tokentype.TokenType) {
	es[e] -= 1
}
func (es *TokenTypeVector) Inc(e tokentype.TokenType) {
	es[e] += 1
}
func (es *TokenTypeVector) Add(e tokentype.TokenType, v int) {
	es[e] += v
}
func (es *TokenTypeVector) SetIfGt(e tokentype.TokenType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es TokenTypeVector) Get(e tokentype.TokenType) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es TokenTypeVector) Iter(fn func(i tokentype.TokenType, v int) bool) bool {
	for i, v := range es {
		if fn(tokentype.TokenType(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es TokenTypeVector) VectorAdd(arg TokenTypeVector) TokenTypeVector {
	var rtn TokenTypeVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es TokenTypeVector) VectorSub(arg TokenTypeVector) TokenTypeVector {
	var rtn TokenTypeVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *TokenTypeVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>TokenType statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return tokentype.TokenType(i).String()
}

var IndexFn = template.FuncMap{
	"TokenTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{TokenTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
