// Code generated by "genenum.exe -typename=ObjectType -packagename=objecttype -basedir=."

package objecttype

import "fmt"

type ObjectType uint8

const (
	NULL_OBJ         ObjectType = iota // NULL
	INTEGER_OBJ                        // INTEGER
	FLOAT_OBJ                          // FLOAT
	BOOLEAN_OBJ                        // BOOLEAN
	RETURN_VALUE_OBJ                   // RETURN_VALUE
	ERROR_OBJ                          // ERROR
	FUNCTION_OBJ                       // FUNCTION
	STRING_OBJ                         // STRING
	BUILTIN_OBJ                        // BUILTIN
	ARRAY_OBJ                          // ARRAY
	HASH_OBJ                           // HASH
	FILE_OBJ                           // FILE
	REGEXP_OBJ                         // REGEXP
	//

	ObjectType_Count int = iota
)

var _ObjectType2string = [ObjectType_Count][2]string{
	NULL_OBJ:         {"NULL_OBJ", "NULL"},
	INTEGER_OBJ:      {"INTEGER_OBJ", "INTEGER"},
	FLOAT_OBJ:        {"FLOAT_OBJ", "FLOAT"},
	BOOLEAN_OBJ:      {"BOOLEAN_OBJ", "BOOLEAN"},
	RETURN_VALUE_OBJ: {"RETURN_VALUE_OBJ", "RETURN_VALUE"},
	ERROR_OBJ:        {"ERROR_OBJ", "ERROR"},
	FUNCTION_OBJ:     {"FUNCTION_OBJ", "FUNCTION"},
	STRING_OBJ:       {"STRING_OBJ", "STRING"},
	BUILTIN_OBJ:      {"BUILTIN_OBJ", "BUILTIN"},
	ARRAY_OBJ:        {"ARRAY_OBJ", "ARRAY"},
	HASH_OBJ:         {"HASH_OBJ", "HASH"},
	FILE_OBJ:         {"FILE_OBJ", "FILE"},
	REGEXP_OBJ:       {"REGEXP_OBJ", "REGEXP"},
}

func (e ObjectType) String() string {
	if e >= 0 && e < ObjectType(ObjectType_Count) {
		return _ObjectType2string[e][0]
	}
	return fmt.Sprintf("ObjectType%d", uint8(e))
}

func (e ObjectType) CommentString() string {
	if e >= 0 && e < ObjectType(ObjectType_Count) {
		return _ObjectType2string[e][1]
	}
	return ""
}

var _string2ObjectType = map[string]ObjectType{
	"NULL_OBJ":         NULL_OBJ,
	"INTEGER_OBJ":      INTEGER_OBJ,
	"FLOAT_OBJ":        FLOAT_OBJ,
	"BOOLEAN_OBJ":      BOOLEAN_OBJ,
	"RETURN_VALUE_OBJ": RETURN_VALUE_OBJ,
	"ERROR_OBJ":        ERROR_OBJ,
	"FUNCTION_OBJ":     FUNCTION_OBJ,
	"STRING_OBJ":       STRING_OBJ,
	"BUILTIN_OBJ":      BUILTIN_OBJ,
	"ARRAY_OBJ":        ARRAY_OBJ,
	"HASH_OBJ":         HASH_OBJ,
	"FILE_OBJ":         FILE_OBJ,
	"REGEXP_OBJ":       REGEXP_OBJ,
}

func String2ObjectType(s string) (ObjectType, bool) {
	v, b := _string2ObjectType[s]
	return v, b
}
