// Code generated by "genenum.exe -typename=TokenType -packagename=tokentype -basedir=enum"

package tokentype

import "fmt"

type TokenType uint8

const (
	ILLEGAL TokenType = iota // ILLEGAL
	EOF                      // EOF
	EOL                      // EOL
	IDENT                    // IDENT
	REGEXP                   // REGEXP
	//
	CASE            // case
	CONST           // const
	DEFAULT         // default
	DEFINE_FUNCTION // function
	ELSE            // else
	FALSE           // false
	FLOAT           // float
	FOR             // for
	FOREACH         // foreach
	FUNCTION        // fn
	IF              // if
	IN              // in
	INT             // int
	LET             // let
	RETURN          // return
	STRING          // string
	SWITCH          // switch
	TRUE            // true
	//
	AND             // &&
	ASSIGN          // =
	ASTERISK        // *
	ASTERISK_EQUALS // *=
	BACKTICK        // `
	BANG            // !
	COLON           // :
	COMMA           // ,
	CONTAINS        // ~=
	DOTDOT          // ..
	EQ              // ==
	GT              // >
	GT_EQUALS       // >=
	LBRACE          // {
	LBRACKET        // [
	LPAREN          // (
	LT              // <
	LT_EQUALS       // <=
	MINUS           // -
	MINUS_EQUALS    // -=
	MINUS_MINUS     // --
	MOD             // %
	NOT_CONTAINS    // !~
	NOT_EQ          // !=
	OR              // ||
	PERIOD          // .
	PLUS            // +
	PLUS_EQUALS     // +=
	PLUS_PLUS       // ++
	POW             // **
	QUESTION        // ?
	RBRACE          // }
	RBRACKET        // ]
	RPAREN          // )
	SEMICOLON       // ;
	SLASH           // /
	SLASH_EQUALS    // /=
	//

	TokenType_Count int = iota
)

var _TokenType2string = [TokenType_Count][2]string{
	ILLEGAL:         {"ILLEGAL", "ILLEGAL"},
	EOF:             {"EOF", "EOF"},
	EOL:             {"EOL", "EOL"},
	IDENT:           {"IDENT", "IDENT"},
	REGEXP:          {"REGEXP", "REGEXP"},
	CASE:            {"CASE", "case"},
	CONST:           {"CONST", "const"},
	DEFAULT:         {"DEFAULT", "default"},
	DEFINE_FUNCTION: {"DEFINE_FUNCTION", "function"},
	ELSE:            {"ELSE", "else"},
	FALSE:           {"FALSE", "false"},
	FLOAT:           {"FLOAT", "float"},
	FOR:             {"FOR", "for"},
	FOREACH:         {"FOREACH", "foreach"},
	FUNCTION:        {"FUNCTION", "fn"},
	IF:              {"IF", "if"},
	IN:              {"IN", "in"},
	INT:             {"INT", "int"},
	LET:             {"LET", "let"},
	RETURN:          {"RETURN", "return"},
	STRING:          {"STRING", "string"},
	SWITCH:          {"SWITCH", "switch"},
	TRUE:            {"TRUE", "true"},
	AND:             {"AND", "&&"},
	ASSIGN:          {"ASSIGN", "="},
	ASTERISK:        {"ASTERISK", "*"},
	ASTERISK_EQUALS: {"ASTERISK_EQUALS", "*="},
	BACKTICK:        {"BACKTICK", "`"},
	BANG:            {"BANG", "!"},
	COLON:           {"COLON", ":"},
	COMMA:           {"COMMA", ","},
	CONTAINS:        {"CONTAINS", "~="},
	DOTDOT:          {"DOTDOT", ".."},
	EQ:              {"EQ", "=="},
	GT:              {"GT", ">"},
	GT_EQUALS:       {"GT_EQUALS", ">="},
	LBRACE:          {"LBRACE", "{"},
	LBRACKET:        {"LBRACKET", "["},
	LPAREN:          {"LPAREN", "("},
	LT:              {"LT", "<"},
	LT_EQUALS:       {"LT_EQUALS", "<="},
	MINUS:           {"MINUS", "-"},
	MINUS_EQUALS:    {"MINUS_EQUALS", "-="},
	MINUS_MINUS:     {"MINUS_MINUS", "--"},
	MOD:             {"MOD", "%"},
	NOT_CONTAINS:    {"NOT_CONTAINS", "!~"},
	NOT_EQ:          {"NOT_EQ", "!="},
	OR:              {"OR", "||"},
	PERIOD:          {"PERIOD", "."},
	PLUS:            {"PLUS", "+"},
	PLUS_EQUALS:     {"PLUS_EQUALS", "+="},
	PLUS_PLUS:       {"PLUS_PLUS", "++"},
	POW:             {"POW", "**"},
	QUESTION:        {"QUESTION", "?"},
	RBRACE:          {"RBRACE", "}"},
	RBRACKET:        {"RBRACKET", "]"},
	RPAREN:          {"RPAREN", ")"},
	SEMICOLON:       {"SEMICOLON", ";"},
	SLASH:           {"SLASH", "/"},
	SLASH_EQUALS:    {"SLASH_EQUALS", "/="},
}

func (e TokenType) String() string {
	if e >= 0 && e < TokenType(TokenType_Count) {
		return _TokenType2string[e][0]
	}
	return fmt.Sprintf("TokenType%d", uint8(e))
}

func (e TokenType) CommentString() string {
	if e >= 0 && e < TokenType(TokenType_Count) {
		return _TokenType2string[e][1]
	}
	return ""
}

var _string2TokenType = map[string]TokenType{
	"ILLEGAL":         ILLEGAL,
	"EOF":             EOF,
	"EOL":             EOL,
	"IDENT":           IDENT,
	"REGEXP":          REGEXP,
	"CASE":            CASE,
	"CONST":           CONST,
	"DEFAULT":         DEFAULT,
	"DEFINE_FUNCTION": DEFINE_FUNCTION,
	"ELSE":            ELSE,
	"FALSE":           FALSE,
	"FLOAT":           FLOAT,
	"FOR":             FOR,
	"FOREACH":         FOREACH,
	"FUNCTION":        FUNCTION,
	"IF":              IF,
	"IN":              IN,
	"INT":             INT,
	"LET":             LET,
	"RETURN":          RETURN,
	"STRING":          STRING,
	"SWITCH":          SWITCH,
	"TRUE":            TRUE,
	"AND":             AND,
	"ASSIGN":          ASSIGN,
	"ASTERISK":        ASTERISK,
	"ASTERISK_EQUALS": ASTERISK_EQUALS,
	"BACKTICK":        BACKTICK,
	"BANG":            BANG,
	"COLON":           COLON,
	"COMMA":           COMMA,
	"CONTAINS":        CONTAINS,
	"DOTDOT":          DOTDOT,
	"EQ":              EQ,
	"GT":              GT,
	"GT_EQUALS":       GT_EQUALS,
	"LBRACE":          LBRACE,
	"LBRACKET":        LBRACKET,
	"LPAREN":          LPAREN,
	"LT":              LT,
	"LT_EQUALS":       LT_EQUALS,
	"MINUS":           MINUS,
	"MINUS_EQUALS":    MINUS_EQUALS,
	"MINUS_MINUS":     MINUS_MINUS,
	"MOD":             MOD,
	"NOT_CONTAINS":    NOT_CONTAINS,
	"NOT_EQ":          NOT_EQ,
	"OR":              OR,
	"PERIOD":          PERIOD,
	"PLUS":            PLUS,
	"PLUS_EQUALS":     PLUS_EQUALS,
	"PLUS_PLUS":       PLUS_PLUS,
	"POW":             POW,
	"QUESTION":        QUESTION,
	"RBRACE":          RBRACE,
	"RBRACKET":        RBRACKET,
	"RPAREN":          RPAREN,
	"SEMICOLON":       SEMICOLON,
	"SLASH":           SLASH,
	"SLASH_EQUALS":    SLASH_EQUALS,
}

func String2TokenType(s string) (TokenType, bool) {
	v, b := _string2TokenType[s]
	return v, b
}
